#!/usr/bin/env bash

set -e

npm install
npm run clean
npm run build

# make current git commit hash available on /_prout for prout
COMMIT_ID=$(git rev-parse HEAD)
echo "{\"gitCommitId\": \"$COMMIT_ID\"}" > dist/_prout
